//! Hypothesis types and the `HypothesisGenerator` trait.
//!
//! Hypothesis generators propose interpretations from different angles,
//! producing `Hypothesis` objects that feed into the evidence evaluator.

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use maple_worldline_observation::PerformanceAnomaly;

use crate::types::{Evidence, HypothesisId, SelfMeaning, SelfMeaningCategory};

// ── Observation Summary ─────────────────────────────────────────────────

/// Simplified view of current observation state for hypothesis generators.
///
/// This provides generators with the context they need without exposing
/// the full observation internals.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ObservationSummary {
    /// Total events observed across all subsystems.
    pub total_events: u64,
    /// Per-subsystem summary views.
    pub subsystem_summaries: HashMap<String, SubsystemSummaryView>,
    /// When this summary was taken.
    pub snapshot_timestamp: DateTime<Utc>,
}

/// Simplified view of a subsystem's observation state.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SubsystemSummaryView {
    /// Number of events observed from this subsystem.
    pub events_observed: u64,
    /// Average latency in nanoseconds.
    pub avg_latency_ns: f64,
    /// Maximum latency in nanoseconds.
    pub max_latency_ns: f64,
    /// Total error count.
    pub error_count: u64,
    /// Error rate (0.0 to 1.0).
    pub error_rate: f64,
}

// ── Hypothesis ──────────────────────────────────────────────────────────

/// A proposed interpretation generated by a hypothesis generator.
///
/// Hypotheses are preliminary — they become `SelfMeaning` objects after
/// evidence evaluation confirms or weakens them.
#[derive(Clone, Debug)]
pub struct Hypothesis {
    /// Unique hypothesis identifier.
    pub id: HypothesisId,
    /// What meaning category this hypothesis proposes.
    pub meaning_category: SelfMeaningCategory,
    /// Initial confidence from the generator (0.0 to 1.0).
    pub confidence: f64,
    /// Evidence that prompted this hypothesis.
    pub evidence: Vec<Evidence>,
    /// Human-readable description of the hypothesis.
    pub description: String,
    /// Name of the generator that produced this.
    pub generator_name: String,
    /// When this hypothesis was generated.
    pub created_at: DateTime<Utc>,
}

// ── Hypothesis Generator Trait ──────────────────────────────────────────

/// Trait for hypothesis generators.
///
/// Multiple generators run in parallel, each proposing interpretations from
/// a different angle. The evidence evaluator and ambiguity manager then
/// determine which hypotheses become established meanings.
pub trait HypothesisGenerator: Send + Sync {
    /// Generate hypotheses from observed anomalies and context.
    ///
    /// # Arguments
    /// - `anomalies`: Currently detected performance anomalies
    /// - `summary`: Current observation summary
    /// - `history`: Past meanings for pattern matching
    fn generate(
        &self,
        anomalies: &[PerformanceAnomaly],
        summary: &ObservationSummary,
        history: &[SelfMeaning],
    ) -> Vec<Hypothesis>;

    /// Generator name (for provenance tracking).
    fn name(&self) -> &str;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn observation_summary_construction() {
        let summary = ObservationSummary {
            total_events: 1000,
            subsystem_summaries: HashMap::new(),
            snapshot_timestamp: Utc::now(),
        };
        assert_eq!(summary.total_events, 1000);
    }

    #[test]
    fn hypothesis_construction() {
        let hyp = Hypothesis {
            id: HypothesisId::new(),
            meaning_category: SelfMeaningCategory::PerformanceBottleneck {
                component: "gate".into(),
                severity: 0.7,
                root_causes: vec![],
            },
            confidence: 0.6,
            evidence: vec![],
            description: "commitment gate is slow".into(),
            generator_name: "test-generator".into(),
            created_at: Utc::now(),
        };
        assert!((hyp.confidence - 0.6).abs() < f64::EPSILON);
        assert_eq!(hyp.generator_name, "test-generator");
    }

    #[test]
    fn subsystem_summary_view() {
        let view = SubsystemSummaryView {
            events_observed: 500,
            avg_latency_ns: 5_000_000.0,
            max_latency_ns: 50_000_000.0,
            error_count: 5,
            error_rate: 0.01,
        };
        assert_eq!(view.events_observed, 500);
        assert!((view.error_rate - 0.01).abs() < f64::EPSILON);
    }
}
